import type { Metadata } from "next";
import "./globals.css";
import { Poppins, Fira_Code } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600"],
  display: "swap",
  variable: "--font-poppins",
  fallback: ["sans-serif"],
});

const firaCode = Fira_Code({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
  variable: "--font-fira-code",
  fallback: ["Courier New", "Courier", "monospace"],
});

export const metadata: Metadata = {
  title: "Laida's Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/images/favicon-porto-laida.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.variable} ${firaCode.variable}`}>
      {/* <html lang="en" className={`${poppins.className}`}> */}
      {/* <body className="antialiased">{children}</body> */}
      <body>{children}</body>
    </html>
  );
}
